name: Deploy & Run K6 Test on EC2

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/Gamegoo-k6-Test"

      - name: Create .env on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "BASE_URL=${{ secrets.BASE_URL }}" > /home/ubuntu/Gamegoo-k6-Test/.env
            echo "K6_PROMETHEUS_RW_SERVER_URL=${{ secrets.K6_PROMETHEUS_RW_SERVER_URL }}" >> /home/ubuntu/Gamegoo-k6-Test/.env
            echo "SUMMARY_API_URL=${{ secrets.SUMMARY_API_URL }}" >> /home/ubuntu/Gamegoo-k6-Test/.env

      # - name: Run test script on EC2
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       cd /home/ubuntu/Gamegoo-k6-Test
      #       npm install
      #       nohup node test/runK6.js > run.log 2>&1 &
